------------SGBD PROIECT--------------


--resetare bd

DROP TABLE UTILIZATOR_GRUP CASCADE CONSTRAINTS;
DROP TABLE UTILIZATOR_CONVERSATIE CASCADE CONSTRAINTS;
DROP TABLE PRIETENIE CASCADE CONSTRAINTS;
DROP TABLE MESAJ CASCADE CONSTRAINTS;
DROP TABLE COMENTARIU CASCADE CONSTRAINTS;
DROP TABLE REACTIE CASCADE CONSTRAINTS;
DROP TABLE POSTARE CASCADE CONSTRAINTS;
DROP TABLE CONVERSATIE CASCADE CONSTRAINTS;
DROP TABLE GRUP CASCADE CONSTRAINTS;
DROP TABLE UTILIZATOR CASCADE CONSTRAINTS;


--------------- creare tabele ----------





CREATE TABLE UTILIZATOR
(
    id_utilizator NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    nume VARCHAR2(256) NOT NULL,
    email VARCHAR2(256) NOT NULL,
    parola VARCHAR2(256) NOT NULL,
    telefon VARCHAR2(10),
    cont_privat NUMBER(1) DEFAULT 0 NOT NULL,
    data_inregistrarii DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_utilizator PRIMARY KEY (id_utilizator),
    CONSTRAINT email_unic UNIQUE (email),
    CONSTRAINT email_valid CHECK (email LIKE '%@%'),
    CONSTRAINT lungime_parola CHECK (LENGTH(parola)>=8),
    CONSTRAINT lungime_telefon CHECK (LENGTH(telefon)=10),
    CONSTRAINT cont_privat CHECK (cont_privat IN (0,1))
);
/


CREATE TABLE GRUP
(
    id_grup NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    nume_grup VARCHAR2(256) NOT NULL,
    descriere VARCHAR2(256) NOT NULL,
    data_crearii DATE DEFAULT  SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_grup PRIMARY KEY (id_grup)
);
/


CREATE TABLE CONVERSATIE
(
    id_conversatie NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    tip_conversatie VARCHAR2(8) NOT NULL,
    data_crearii DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_conversatie PRIMARY KEY (id_conversatie),
    CONSTRAINT verificare_tip_conversatie CHECK ( tip_conversatie  IN ('GRUP','PRIVAT'))
);
/


CREATE TABLE POSTARE
(
    id_postare NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    id_utilizator NUMBER(10) NOT NULL,
    id_grup NUMBER(10),--poate fi null
    continut_text VARCHAR2(256) NOT NULL,
    fisier VARCHAR2(256),
    tip_media VARCHAR2(4),
    data_postarii DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_postare PRIMARY KEY (id_postare),
    CONSTRAINT cheie_straina_postare_utilizator FOREIGN KEY  (id_utilizator) REFERENCES UTILIZATOR(id_utilizator) ON DELETE CASCADE,
    CONSTRAINT cheie_straina_postare_grup FOREIGN KEY (id_grup) REFERENCES GRUP(id_grup) ON DELETE SET NULL,
    CONSTRAINT verificare_tip_media CHECK ( tip_media IN ('IMG','VID'))
);
/


CREATE TABLE COMENTARIU
(
    id_comentariu NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    id_utilizator NUMBER(10) NOT NULL,
    id_postare NUMBER(10) NOT NULL,
    continut_text VARCHAR2(256) NOT NULL,
    data_postarii DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_comentariu PRIMARY KEY (id_comentariu),
    CONSTRAINT cheie_straina_comentariu_utilizator FOREIGN KEY (id_utilizator) REFERENCES UTILIZATOR(id_utilizator) ON DELETE CASCADE,
    CONSTRAINT cheie_straina_comentariu_postare FOREIGN KEY (id_postare) REFERENCES POSTARE(id_postare) ON DELETE CASCADE
);
/


CREATE TABLE REACTIE
(
    id_reactie NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    id_utilizator NUMBER(10) NOT NULL,
    id_postare NUMBER(10) NOT NULL,
    tip_reactie VARCHAR2(16),
    data_trimiterii DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_reactie PRIMARY KEY (id_reactie),
    CONSTRAINT cheie_straina_reactie_utilizator FOREIGN KEY (id_utilizator) REFERENCES UTILIZATOR(id_utilizator) ON DELETE CASCADE,
    CONSTRAINT cheie_straina_reactie_postare FOREIGN KEY (id_postare) REFERENCES POSTARE(id_postare) ON DELETE CASCADE,
    CONSTRAINT verificare_reactie CHECK ( tip_reactie in ('APRECIERE','AMUZANT','INTERESANT'))
);
/

CREATE TABLE MESAJ
(
    id_mesaj NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    id_conversatie NUMBER(10) NOT NULL,
    id_expeditor NUMBER(10) NOT NULL,
    continut_text VARCHAR2(256) NOT NULL,
    data_trimiterii DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_mesaj PRIMARY KEY (id_mesaj),
    CONSTRAINT cheie_straina_mesaj_utilizator FOREIGN KEY (id_expeditor) REFERENCES UTILIZATOR(id_utilizator) ON DELETE CASCADE,
    CONSTRAINT cheie_straina_mesaj_conversatie FOREIGN KEY (id_conversatie) REFERENCES  CONVERSATIE(id_conversatie) ON DELETE CASCADE
);
/

CREATE TABLE PRIETENIE
(
    id_prietenie NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    id_utilizator NUMBER(10) NOT NULL,
    id_prieten NUMBER(10) NOT NULL,
    status VARCHAR2(16) DEFAULT 'ASTEPTARE' NOT NULL,
    data_trimiterii DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_prietenie PRIMARY KEY (id_prietenie),
    CONSTRAINT cheie_straina_prietenie_utilizator FOREIGN KEY (id_utilizator) REFERENCES  UTILIZATOR(id_utilizator) ON DELETE  CASCADE,
    CONSTRAINT cheie_straina_prietenie_prieten FOREIGN KEY (id_prieten) REFERENCES UTILIZATOR(id_utilizator) ON DELETE CASCADE,
    CONSTRAINT verificare_prieteni_diferiti CHECK (id_utilizator != id_prieten),
    CONSTRAINT verificare_status CHECK (status IN ('ASTEPTARE', 'ACCEPTAT','RESPINS'))
);
/



CREATE TABLE UTILIZATOR_GRUP
(
    id_utilizator NUMBER(10) NOT NULL,
    id_grup NUMBER(10) NOT NULL,
    rol VARCHAR2(20) DEFAULT 'MEMBRU' NOT NULL,
    data_aderarii DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_utilizator_grup PRIMARY KEY (id_utilizator,id_grup),
    CONSTRAINT cheie_straina_utilizator_grup_utilizator FOREIGN KEY (id_utilizator) REFERENCES UTILIZATOR(id_utilizator) ON DELETE CASCADE,
    CONSTRAINT cheie_straina_utilizator_grup_grup FOREIGN KEY (id_grup) REFERENCES GRUP(id_grup) ON DELETE CASCADE,
    CONSTRAINT verificare_rol CHECK ( rol IN ('MEMBRU','ADMIN'))
);
/

CREATE TABLE UTILIZATOR_CONVERSATIE
(
    id_utilizator NUMBER(10) NOT NULL,
    id_conversatie NUMBER(10) NOT NULL,
    CONSTRAINT cheie_primara_utilizator_conversatie PRIMARY KEY (id_utilizator,id_conversatie),
    CONSTRAINT cheie_straina_utilizator_conversatie_utilizator FOREIGN KEY (id_utilizator) REFERENCES UTILIZATOR(id_utilizator) ON DELETE CASCADE,
    CONSTRAINT cheie_straina_utilizator_conversatie_conversatie FOREIGN KEY (id_conversatie) REFERENCES  CONVERSATIE(id_conversatie) ON DELETE CASCADE
);
/



commit;