------------SGBD PROIECT--------------

--Donea Fernando-Emanuel
--Seria 24
--Grupa 243

-- ex 4
--Implementați în Oracle diagrama conceptuală realizată: definiți toate tabelele,
-- adăugând toate constrângerile de integritate necesare
-- (chei primare, cheile externe etc).


--resetare bd

-- DROP TABLE UTILIZATOR_GRUP CASCADE CONSTRAINTS;
-- DROP TABLE UTILIZATOR_CONVERSATIE CASCADE CONSTRAINTS;
-- DROP TABLE PRIETENIE CASCADE CONSTRAINTS;
-- DROP TABLE MESAJ CASCADE CONSTRAINTS;
-- DROP TABLE COMENTARIU CASCADE CONSTRAINTS;
-- DROP TABLE REACTIE CASCADE CONSTRAINTS;
-- DROP TABLE POSTARE CASCADE CONSTRAINTS;
-- DROP TABLE CONVERSATIE CASCADE CONSTRAINTS;
-- DROP TABLE GRUP CASCADE CONSTRAINTS;
-- DROP TABLE UTILIZATOR CASCADE CONSTRAINTS;


--------------- creare tabele ----------

CREATE TABLE UTILIZATOR
(
    id_utilizator NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    nume VARCHAR2(256) NOT NULL,
    email VARCHAR2(256) NOT NULL,
    parola VARCHAR2(256) NOT NULL,
    telefon VARCHAR2(10),
    cont_privat NUMBER(1) DEFAULT 0 NOT NULL,
    data_inregistrarii DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_utilizator PRIMARY KEY (id_utilizator),
    CONSTRAINT email_unic UNIQUE (email),
    CONSTRAINT email_valid CHECK (email LIKE '%@%'),
    CONSTRAINT lungime_parola CHECK (LENGTH(parola)>=8),
    CONSTRAINT lungime_telefon CHECK (LENGTH(telefon)=10),
    CONSTRAINT cont_privat CHECK (cont_privat IN (0,1))
);
/


CREATE TABLE GRUP
(
    id_grup NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    nume_grup VARCHAR2(256) NOT NULL,
    descriere VARCHAR2(256) NOT NULL,
    data_crearii DATE DEFAULT  SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_grup PRIMARY KEY (id_grup)
);
/


CREATE TABLE CONVERSATIE
(
    id_conversatie NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    tip_conversatie VARCHAR2(8) NOT NULL,
    data_crearii DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_conversatie PRIMARY KEY (id_conversatie),
    CONSTRAINT verificare_tip_conversatie CHECK ( tip_conversatie  IN ('GRUP','PRIVAT'))
);
/


CREATE TABLE POSTARE
(
    id_postare NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    id_utilizator NUMBER(10) NOT NULL,
    id_grup NUMBER(10),--poate fi null
    continut_text VARCHAR2(256) NOT NULL,
    fisier VARCHAR2(256),
    tip_media VARCHAR2(4),
    data_postarii DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_postare PRIMARY KEY (id_postare),
    CONSTRAINT cheie_straina_postare_utilizator FOREIGN KEY  (id_utilizator) REFERENCES UTILIZATOR(id_utilizator) ON DELETE CASCADE,
    CONSTRAINT cheie_straina_postare_grup FOREIGN KEY (id_grup) REFERENCES GRUP(id_grup) ON DELETE SET NULL,
    CONSTRAINT verificare_tip_media CHECK ( tip_media IN ('IMG','VID'))
);
/


CREATE TABLE COMENTARIU
(
    id_comentariu NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    id_utilizator NUMBER(10) NOT NULL,
    id_postare NUMBER(10) NOT NULL,
    continut_text VARCHAR2(256) NOT NULL,
    data_postarii DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_comentariu PRIMARY KEY (id_comentariu),
    CONSTRAINT cheie_straina_comentariu_utilizator FOREIGN KEY (id_utilizator) REFERENCES UTILIZATOR(id_utilizator) ON DELETE CASCADE,
    CONSTRAINT cheie_straina_comentariu_postare FOREIGN KEY (id_postare) REFERENCES POSTARE(id_postare) ON DELETE CASCADE
);
/


CREATE TABLE REACTIE
(
    id_reactie NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    id_utilizator NUMBER(10) NOT NULL,
    id_postare NUMBER(10) NOT NULL,
    tip_reactie VARCHAR2(16),
    data_trimiterii DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_reactie PRIMARY KEY (id_reactie),
    CONSTRAINT cheie_straina_reactie_utilizator FOREIGN KEY (id_utilizator) REFERENCES UTILIZATOR(id_utilizator) ON DELETE CASCADE,
    CONSTRAINT cheie_straina_reactie_postare FOREIGN KEY (id_postare) REFERENCES POSTARE(id_postare) ON DELETE CASCADE,
    CONSTRAINT verificare_reactie CHECK ( tip_reactie in ('APRECIERE','AMUZANT','INTERESANT'))
);
/

CREATE TABLE MESAJ
(
    id_mesaj NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    id_conversatie NUMBER(10) NOT NULL,
    id_expeditor NUMBER(10) NOT NULL,
    continut_text VARCHAR2(256) NOT NULL,
    data_trimiterii DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_mesaj PRIMARY KEY (id_mesaj),
    CONSTRAINT cheie_straina_mesaj_utilizator FOREIGN KEY (id_expeditor) REFERENCES UTILIZATOR(id_utilizator) ON DELETE CASCADE,
    CONSTRAINT cheie_straina_mesaj_conversatie FOREIGN KEY (id_conversatie) REFERENCES  CONVERSATIE(id_conversatie) ON DELETE CASCADE
);
/

CREATE TABLE PRIETENIE
(
    id_prietenie NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    id_utilizator NUMBER(10) NOT NULL,
    id_prieten NUMBER(10) NOT NULL,
    status VARCHAR2(16) DEFAULT 'ASTEPTARE' NOT NULL,
    data_trimiterii DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_prietenie PRIMARY KEY (id_prietenie),
    CONSTRAINT cheie_straina_prietenie_utilizator FOREIGN KEY (id_utilizator) REFERENCES  UTILIZATOR(id_utilizator) ON DELETE  CASCADE,
    CONSTRAINT cheie_straina_prietenie_prieten FOREIGN KEY (id_prieten) REFERENCES UTILIZATOR(id_utilizator) ON DELETE CASCADE,
    CONSTRAINT verificare_prieteni_diferiti CHECK (id_utilizator != id_prieten),
    CONSTRAINT verificare_status CHECK (status IN ('ASTEPTARE', 'ACCEPTAT','RESPINS'))
);
/



CREATE TABLE UTILIZATOR_GRUP
(
    id_utilizator NUMBER(10) NOT NULL,
    id_grup NUMBER(10) NOT NULL,
    rol VARCHAR2(20) DEFAULT 'MEMBRU' NOT NULL,
    data_aderarii DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT cheie_primara_utilizator_grup PRIMARY KEY (id_utilizator,id_grup),
    CONSTRAINT cheie_straina_utilizator_grup_utilizator FOREIGN KEY (id_utilizator) REFERENCES UTILIZATOR(id_utilizator) ON DELETE CASCADE,
    CONSTRAINT cheie_straina_utilizator_grup_grup FOREIGN KEY (id_grup) REFERENCES GRUP(id_grup) ON DELETE CASCADE,
    CONSTRAINT verificare_rol CHECK ( rol IN ('MEMBRU','ADMIN'))
);
/

CREATE TABLE UTILIZATOR_CONVERSATIE
(
    id_utilizator NUMBER(10) NOT NULL,
    id_conversatie NUMBER(10) NOT NULL,
    CONSTRAINT cheie_primara_utilizator_conversatie PRIMARY KEY (id_utilizator,id_conversatie),
    CONSTRAINT cheie_straina_utilizator_conversatie_utilizator FOREIGN KEY (id_utilizator) REFERENCES UTILIZATOR(id_utilizator) ON DELETE CASCADE,
    CONSTRAINT cheie_straina_utilizator_conversatie_conversatie FOREIGN KEY (id_conversatie) REFERENCES  CONVERSATIE(id_conversatie) ON DELETE CASCADE
);
/






--ex 5
-- Adăugați informații coerente în tabelele create
-- (minim 5 înregistrări pentru fiecare entitateindependentă;
-- minim 10 înregistrări pentru fiecare tabelă asociativă).



-- Inserari



----------------------- CREAREA UTILIZATORILOR -----------------------

INSERT INTO UTILIZATOR (nume, email, parola, telefon, cont_privat, data_inregistrarii)
VALUES (
        'Andrei Popescu',
        'andreipopescu@yahoo.com',
        'Andrei111',
        '0711111111',
        0,
        TO_DATE('01-03-2024','DD-MM-YYYY')
       );

INSERT INTO UTILIZATOR (nume, email, parola, telefon, cont_privat, data_inregistrarii)
VALUES (
        'Nicusor Ghita',
        'nicughita@gmail.com',
        'Nicu2022',
        '0722222222',
        1,
        TO_DATE('02-03-2024','DD-MM-YYYY')
       );
INSERT INTO UTILIZATOR (nume, email, parola, telefon, cont_privat, data_inregistrarii)
VALUES (
        'Ana Marinescu',
        'anamarinescu@outlook.com',
        'ParolaParola',
        '0733333333',
        0,
        TO_DATE('01-04-2024','DD-MM-YYYY')
       );
INSERT INTO UTILIZATOR (nume, email, parola, telefon, cont_privat, data_inregistrarii)
VALUES (
        'Mihaela Popa',
        'miha_popa@gmail.com',
        'Azorel2008',
        '0744444444',
        1,
        TO_DATE('02-04-2024','DD-MM-YYYY')
       );


INSERT INTO UTILIZATOR (nume, email, parola, telefon, cont_privat, data_inregistrarii)
VALUES (
        'Fernando Donea',
        'fernando@gmail.com',
        'Parola123123',
        '0777123123',
        0,
        TO_DATE('01-05-2024','DD-MM-YYYY')
       );

INSERT INTO UTILIZATOR (nume, email, parola, telefon, cont_privat, data_inregistrarii)
VALUES (
        'Gigel Gigel',
        'gigi@yahoo.com',
        'GigiProgramatoru',
        '0774567891',
        0,
        TO_DATE('02-05-2024','DD-MM-YYYY')
       );
INSERT INTO UTILIZATOR (nume, email, parola, telefon, cont_privat, data_inregistrarii)
VALUES (
        'Utilizator Inactiv',
        'inactiv@yahoo.com',
        'Parola123123',
        '0774567231',
        0,
        TO_DATE('04-02-2024','DD-MM-YYYY')
       );
/


commit;



-----------------------CREAREA GRUPURILOR SI INTRAREA UTILIZATORILOR IN GRUP-----------------------


----------------


INSERT INTO GRUP (nume_grup, descriere, data_crearii)
VALUES (
        'Programatorii ASC',
        'Discutii despre arhitectura sistemelor de calcul',
        TO_DATE('05-03-2024','DD-MM-YYYY')
       );

--Andrei creeaza programatorii ASC
INSERT INTO UTILIZATOR_GRUP (id_utilizator, id_grup, rol, data_aderarii)
VALUES (1,1,'ADMIN',TO_DATE('05-03-2024','DD-MM-YYYY'));

--Nicusor intra in programtorii asc
INSERT INTO UTILIZATOR_GRUP (id_utilizator, id_grup, rol, data_aderarii)
VALUES (2,1,'MEMBRU',TO_DATE('10-03-2024','DD-MM-YYYY'));

--Fernando intra in programtorii asc mai tarziu
INSERT INTO UTILIZATOR_GRUP (id_utilizator, id_grup, rol, data_aderarii)
VALUES (5,1,'MEMBRU',TO_DATE('03-05-2024','DD-MM-YYYY'));

--Gigel intra in programatorii asc mai tarziu
INSERT INTO UTILIZATOR_GRUP (id_utilizator, id_grup, rol, data_aderarii)
VALUES (6,1,'MEMBRU',TO_DATE('04-05-2024','DD-MM-YYYY'));


---------------


INSERT INTO GRUP (nume_grup, descriere, data_crearii)
VALUES (
        'Fotografii de la FMI',
        'Poze si videoclipuri ale studentilor de la FMI',
        TO_DATE('06-03-2024','DD-MM-YYYY')
       );


-- Andrei creeaza fotografii de la fmi
INSERT INTO UTILIZATOR_GRUP (id_utilizator, id_grup, rol, data_aderarii)
VALUES (1,2,'ADMIN',TO_DATE('06-03-2024','DD-MM-YYYY'));

--Ana intra in fotografii de la fmi
INSERT INTO UTILIZATOR_GRUP (id_utilizator, id_grup, rol, data_aderarii)
VALUES (3,2,'MEMBRU',TO_DATE('03-04-2024','DD-MM-YYYY'));


---------------


INSERT INTO GRUP (nume_grup, descriere, data_crearii)
VALUES (
        'Calatorii si diverse',
        'Poze din diverse locuri interesante',
        TO_DATE('05-04-2024','DD-MM-YYYY')
       );


--Nicusor creeaza grupul calatorii si diverse
INSERT INTO UTILIZATOR_GRUP (id_utilizator, id_grup, rol, data_aderarii)
VALUES (2,3,'ADMIN',TO_DATE('05-04-2024','DD-MM-YYYY'));

--Mihaela intra in calatorii
INSERT INTO UTILIZATOR_GRUP (id_utilizator, id_grup, rol, data_aderarii)
VALUES (4,3,'MEMBRU',TO_DATE('04-04-2024','DD-MM-YYYY'));


---------------


INSERT INTO GRUP (nume_grup, descriere, data_crearii)
VALUES (
        'Filme bune',
        'Recomandari de filme bune si de seriale de vizionar',
        TO_DATE('06-04-2024','DD-MM-YYYY')
       );

--Nicusor creeaza grupul filme bune
INSERT INTO UTILIZATOR_GRUP (id_utilizator, id_grup, rol, data_aderarii)
VALUES (2,4,'ADMIN',TO_DATE('06-04-2024','DD-MM-YYYY'));


--Gigel intra in filme bune
INSERT INTO UTILIZATOR_GRUP (id_utilizator, id_grup, rol, data_aderarii)
VALUES (6,4,'MEMBRU',TO_DATE('04-05-2024','DD-MM-YYYY'));


---------------


INSERT INTO GRUP (nume_grup, descriere, data_crearii)
VALUES (
        'Club de lectura',
        'Discutii rapide despre carti citite',
        TO_DATE('05-05-2024','DD-MM-YYYY')
       );

--Ana creeaza grupul clubul de lectura
INSERT INTO UTILIZATOR_GRUP (id_utilizator, id_grup, rol, data_aderarii)
VALUES (3,5,'ADMIN',TO_DATE('05-05-2024','DD-MM-YYYY'));


commit;




---------------------------- RELATIILE DE PRIETENIE   --------------------------



--Andrei-Nicusor
INSERT INTO PRIETENIE (ID_UTILIZATOR, ID_PRIETEN, STATUS, DATA_TRIMITERII)
VALUES (1, 2 , 'ACCEPTAT', TO_DATE('15-03-2024','DD-MM-YYYY'));

--Ana-Mihaela
INSERT INTO PRIETENIE (ID_UTILIZATOR, ID_PRIETEN, STATUS, DATA_TRIMITERII)
VALUES (3, 4 , 'ACCEPTAT', TO_DATE('10-04-2024','DD-MM-YYYY'));

--Fernando-Gigel
INSERT INTO PRIETENIE (ID_UTILIZATOR, ID_PRIETEN, STATUS, DATA_TRIMITERII)
VALUES (5, 6 , 'ACCEPTAT', TO_DATE('05-05-2024','DD-MM-YYYY'));


--Fernando-Andrei
INSERT INTO PRIETENIE (ID_UTILIZATOR, ID_PRIETEN, STATUS, DATA_TRIMITERII)
VALUES (1, 5 , 'ACCEPTAT', TO_DATE('10-05-2024','DD-MM-YYYY'));


--Gigel ii trimite o cerere lui Andrei
INSERT INTO PRIETENIE (ID_UTILIZATOR, ID_PRIETEN, STATUS, DATA_TRIMITERII)
VALUES (6, 1 , 'ASTEPTARE', TO_DATE('06-05-2024','DD-MM-YYYY'));

--Nicusor ii respige Mihaelei
INSERT INTO PRIETENIE (ID_UTILIZATOR, ID_PRIETEN, STATUS, DATA_TRIMITERII)
VALUES (2, 4 , 'RESPINS', TO_DATE('15-04-2024','DD-MM-YYYY'));


commit;


---------------------- CONVERSATII SI MESAJE -------------------------





--Conversatie privata dintre Andrei si Nicusor
INSERT INTO CONVERSATIE (tip_conversatie, data_crearii)
VALUES ('PRIVAT',TO_DATE('20-03-2024','DD-MM-YYYY'));

INSERT INTO UTILIZATOR_CONVERSATIE (ID_UTILIZATOR, ID_CONVERSATIE) VALUES (1, 1);--Andrei
INSERT INTO UTILIZATOR_CONVERSATIE (ID_UTILIZATOR, ID_CONVERSATIE) VALUES (2, 1);--Nicusor


INSERT INTO MESAJ (id_conversatie, id_expeditor, continut_text, data_trimiterii)
VALUES (1,1,'Buna Nicusor! Ce faci?',TO_DATE('20-03-2024','DD-MM-YYYY'));

INSERT INTO MESAJ (id_conversatie, id_expeditor, continut_text, data_trimiterii)
VALUES (1,2,'Lucram la un proiect! Tu ce faci, Andrei?',TO_DATE('20-03-2024','DD-MM-YYYY'));


---------------


--Conversatie de grup (Andrei, Nicusor, Ana)
INSERT INTO CONVERSATIE (tip_conversatie, data_crearii)
VALUES ('GRUP',TO_DATE('20-04-2024','DD-MM-YYYY'));

INSERT INTO UTILIZATOR_CONVERSATIE (ID_UTILIZATOR, ID_CONVERSATIE) VALUES (1, 2);--Andrei
INSERT INTO UTILIZATOR_CONVERSATIE (ID_UTILIZATOR, ID_CONVERSATIE) VALUES (2, 2);--Nicusor
INSERT INTO UTILIZATOR_CONVERSATIE (ID_UTILIZATOR, ID_CONVERSATIE) VALUES (3, 2);--Ana

INSERT INTO MESAJ (id_conversatie, id_expeditor, continut_text, data_trimiterii)
VALUES (2,3,'Salutari tuturor!',TO_DATE('25-04-2024','DD-MM-YYYY'));





---------------


--Conversatie privata intre Ana si Mihaela
INSERT INTO CONVERSATIE (tip_conversatie, data_crearii)
VALUES ('PRIVAT',TO_DATE('25-04-2024','DD-MM-YYYY'));

INSERT INTO UTILIZATOR_CONVERSATIE (ID_UTILIZATOR, ID_CONVERSATIE) VALUES (3, 3);--Ana
INSERT INTO UTILIZATOR_CONVERSATIE (ID_UTILIZATOR, ID_CONVERSATIE) VALUES (4, 3);--Mihaela

INSERT INTO MESAJ (id_conversatie, id_expeditor, continut_text, data_trimiterii)
VALUES (3,3,'Buna Mihaela! Mergem si noi la munte?',TO_DATE('26-04-2024','DD-MM-YYYY'));


---------------


--Conversatie privata intre Fernando si Gigel
INSERT INTO CONVERSATIE (tip_conversatie, data_crearii)
VALUES ('PRIVAT',TO_DATE('10-05-2024','DD-MM-YYYY'));

INSERT INTO UTILIZATOR_CONVERSATIE (ID_UTILIZATOR, ID_CONVERSATIE) VALUES (5, 4);--Fernando
INSERT INTO UTILIZATOR_CONVERSATIE (ID_UTILIZATOR, ID_CONVERSATIE) VALUES (6, 4);--Gigel


INSERT INTO MESAJ (id_conversatie, id_expeditor, continut_text, data_trimiterii)
VALUES (4,6,'Fernando, mergem la film maine?',TO_DATE('11-05-2024','DD-MM-YYYY'));

INSERT INTO MESAJ (id_conversatie, id_expeditor, continut_text, data_trimiterii)
VALUES (4,5,'Nu pot maine. Hai poimaine!',TO_DATE('11-05-2024','DD-MM-YYYY'));


---------------


--Conversatie de grup (Andrei, Nicusor, Fernando, Gigel)
INSERT INTO CONVERSATIE (tip_conversatie, data_crearii)
VALUES ('GRUP',TO_DATE('15-05-2024','DD-MM-YYYY'));

INSERT INTO UTILIZATOR_CONVERSATIE (ID_UTILIZATOR, ID_CONVERSATIE) VALUES (1, 5);--Andrei
INSERT INTO UTILIZATOR_CONVERSATIE (ID_UTILIZATOR, ID_CONVERSATIE) VALUES (2, 5);--Nicusor
INSERT INTO UTILIZATOR_CONVERSATIE (ID_UTILIZATOR, ID_CONVERSATIE) VALUES (5, 5);--Fernando
INSERT INTO UTILIZATOR_CONVERSATIE (ID_UTILIZATOR, ID_CONVERSATIE) VALUES (6, 5);--Gigel


INSERT INTO MESAJ (id_conversatie, id_expeditor, continut_text, data_trimiterii)
VALUES (5,6,'Cine merge la Dune 2 maine?',TO_DATE('16-05-2024','DD-MM-YYYY'));


---------------


--Conversatie privata intre Andrei si Fernando
INSERT INTO CONVERSATIE (tip_conversatie, data_crearii)
VALUES ('PRIVAT',TO_DATE('16-05-2024','DD-MM-YYYY'));

INSERT INTO UTILIZATOR_CONVERSATIE (ID_UTILIZATOR, ID_CONVERSATIE) VALUES (1, 6);--Andrei
INSERT INTO UTILIZATOR_CONVERSATIE (ID_UTILIZATOR, ID_CONVERSATIE) VALUES (5, 6);--Fernando

INSERT INTO MESAJ (id_conversatie, id_expeditor, continut_text, data_trimiterii)
VALUES (6,1,'Salut Fernando! Rezolvarea e simpla: MOV EAX EBX. Succes',TO_DATE('16-05-2024','DD-MM-YYYY'));




commit;







------------------------------POSTARI, REACTII SI COMENTARII ---------------------------


--Andrei posteaza pe grupul Programatorii ASC
INSERT INTO POSTARE (id_utilizator, id_grup, continut_text, fisier, tip_media,data_postarii)
VALUES(
       1, 1,
       'Bine ati venit pe grupul de ASC!',
       NULL, NULL,
        TO_DATE('10-03-2024','DD-MM-YYYY')
      );

--Nicusor comenteaza la postarea lui Andrei
INSERT INTO COMENTARIU (id_utilizator, id_postare, continut_text, data_postarii)
VALUES (2,1,
        'Multumim, Andrei!',
        TO_DATE('11-03-2024','DD-MM-YYYY')
       );

--Nicusor apreciaza postarea lui Andrei
INSERT INTO REACTIE (id_utilizator, id_postare, tip_reactie, data_trimiterii)
VALUES (2,1,'APRECIERE',TO_DATE('11-03-2024','DD-MM-YYYY'));


--Fernando reactioneaza cu Interesant la postarea lui Andrei
INSERT INTO REACTIE (id_utilizator, id_postare, tip_reactie, data_trimiterii)
VALUES (5,1,'INTERESANT',TO_DATE('03-05-2024','DD-MM-YYYY'));


---------------


--Nicusor posteaza in grupul Calatorii
INSERT INTO POSTARE (id_utilizator, id_grup, continut_text, fisier, tip_media,data_postarii)
VALUES(
       2, 3,
       'Saptamana trecuta am fost la munte. M-am dat si cu ski-urile',
       'munte.jpg', 'IMG',
        TO_DATE('10-04-2024','DD-MM-YYYY')
      );

--Mihaela aperciaza postarea lui Nicusor
INSERT INTO REACTIE (id_utilizator, id_postare, tip_reactie, data_trimiterii)
VALUES (4,2,'APRECIERE',TO_DATE('11-04-2024','DD-MM-YYYY'));

--Mihaela comenteaza la postarea lui Nicusor
INSERT INTO COMENTARIU (id_utilizator, id_postare, continut_text, data_postarii)
VALUES (4,2,
        'Foarte frumos peisajul. Ar intra niste aer curat la munte',
        TO_DATE('11-04-2024','DD-MM-YYYY')
       );


-------------------


--Ana posteaza pe profil
INSERT INTO POSTARE (id_utilizator, id_grup, continut_text, fisier, tip_media,data_postarii)
VALUES(
       3, NULL,
       'Prima mea postare profil!',
       NULL, NULL,
        TO_DATE('20-04-2024','DD-MM-YYYY')
      );

--Mihaela apreciaza postarea Anei de pe profil
INSERT INTO REACTIE (id_utilizator, id_postare, tip_reactie, data_trimiterii)
VALUES (4,3,'APRECIERE',TO_DATE('21-04-2024','DD-MM-YYYY'));


--Mihaela comenteaza la postarea Anei de pe profli
INSERT INTO COMENTARIU (id_utilizator, id_postare, continut_text, data_postarii)
VALUES (4,3,
        'Bine ai venit Ana!',
        TO_DATE('21-04-2024','DD-MM-YYYY')
       );


--------------------


--Ana posteaza pe clubul de lectura
INSERT INTO POSTARE (id_utilizator, id_grup, continut_text, fisier, tip_media,data_postarii)
VALUES(
       3, 5,
       'Ce ati citit interesant in utlima vreme?',
       NULL, NULL,
        TO_DATE('10-05-2024','DD-MM-YYYY')
      );


----------------------


--Fernando posteaza pe profil
INSERT INTO POSTARE (id_utilizator, id_grup, continut_text, fisier, tip_media,data_postarii)
VALUES(
       5, NULL,
       'Am fost la un concert in acest weekend. A fost super',
       'concert.mp4', 'VID',
        TO_DATE('12-05-2024','DD-MM-YYYY')
      );


-------------------------


--Fernando posteaza pe ASC
INSERT INTO POSTARE (id_utilizator, id_grup, continut_text, fisier, tip_media,data_postarii)
VALUES(
       5, 1,
       'As avea nevoie de ajutor cu ultimul exercitiul din laboratul 5. Ma poatea ajuta cineva?',
       'laborator5.jpg', 'IMG',
        TO_DATE('15-05-2024','DD-MM-YYYY')
      );


--Andrei apreciaza postarea lui Fernando
INSERT INTO REACTIE (id_utilizator, id_postare, tip_reactie, data_trimiterii)
VALUES (1,6,'INTERESANT',TO_DATE('15-05-2024','DD-MM-YYYY'));

--Andrei ii raspunde lui Fernando la postarea despre labul asc
INSERT INTO COMENTARIU (id_utilizator, id_postare, continut_text, data_postarii)
VALUES (1,6,
        'Ti-am dat mesaj cu rezolvarea pe privat',
        TO_DATE('16-05-2024','DD-MM-YYYY')
       );
--Fernando ii multumeste lui Andrei
INSERT INTO COMENTARIU (id_utilizator, id_postare, continut_text, data_postarii)
VALUES (5,6,
        'Mersi mult!',
        TO_DATE('16-05-2024','DD-MM-YYYY')
       );


---------------------


--Gigel posteaza in filme
INSERT INTO POSTARE (id_utilizator, id_grup, continut_text, fisier, tip_media,data_postarii)
VALUES(
       6, 4,
       'Recomand filmul Dune 2. L-am vazut la cinema si chiar mi a placut',
       NULL, NULL,
        TO_DATE('20-05-2024','DD-MM-YYYY')
      );

--Nicusor ii comenteaza lui Gigel
INSERT INTO COMENTARIU (id_utilizator, id_postare, continut_text, data_postarii)
VALUES (2,7,
        'Ar trebui sa ma uit si eu atunci!',
        TO_DATE('21-05-2024','DD-MM-YYYY')
       );



commit;




-- ex 6
-- Formulați în limbaj natural o problemă pe care să o rezolvați folosind un subprogram stocat
-- independent care să utilizeze toate cele 3 tipuri de colecții studiate. Apelați subprogramul.

-- Enunțul problemei:
--Se dorește implementarea unei funcționalități de afișare a profilului complet pentru un utilizator specificat prin ID.
-- Procedura trebuie să afișeze lista de prieteni a utilizatorului (folosind tablouri imbricate),
-- ultimele 3 grupuri în care a intrat utilizatorul (folosind vectori)
-- si o statistică a activității sale, adică numărul de postări și comentarii (folosind tablouri indexate).



CREATE OR REPLACE PROCEDURE p_afisare_profil_utilizator(
    p_id_utilizator IN UTILIZATOR.ID_UTILIZATOR%type
) IS

    --tablou imbricat pentru lista de prieteni
    TYPE t_lista_prieteni IS TABLE OF VARCHAR2(256);
    v_prieteni t_lista_prieteni :=t_lista_prieteni();

    -- vector pentru ultimele 3 grupuri
    TYPE t_istoric_grupuri IS VARRAY(3) OF VARCHAR2(256);
    v_grupuri t_istoric_grupuri := t_istoric_grupuri();

    --tablou indexat pentru statisca activitatii
    TYPE t_statistici IS TABLE OF NUMBER INDEX BY VARCHAR2(64);
    v_statistica t_statistici;

    v_nume_utilizator UTILIZATOR.NUME%type;

BEGIN

    --gasirea numelui utilizatorului
    SELECT NUME
    INTO v_nume_utilizator
    FROM UTILIZATOR
    WHERE ID_UTILIZATOR=p_id_utilizator;

    DBMS_OUTPUT.PUT_LINE('----------------------------------------');
    DBMS_OUTPUT.PUT_LINE('PROFIL UTILIZATOR: ' || v_nume_utilizator);
    DBMS_OUTPUT.PUT_LINE('----------------------------------------');
    DBMS_OUTPUT.PUT_LINE(' ');


    FOR rezultat IN
        (
            --cautam prietenii
            SELECT U.NUME
            FROM PRIETENIE P
            JOIN UTILIZATOR U ON P.ID_PRIETEN = U.ID_UTILIZATOR
            WHERE P.ID_UTILIZATOR=p_id_utilizator AND P.STATUS='ACCEPTAT'

            UNION

            SELECT U2.NUME
            FROM PRIETENIE P2
            JOIN UTILIZATOR U2 ON P2.ID_UTILIZATOR=U2.ID_UTILIZATOR
            WHERE P2.ID_PRIETEN=p_id_utilizator AND P2.STATUS='ACCEPTAT'

        ) LOOP
            v_prieteni.EXTEND;
            v_prieteni(v_prieteni.LAST):=rezultat.NUME;
        end loop;

    --Afisam prietenii
    DBMS_OUTPUT.PUT_LINE('LISTA PRIETENI:' || v_prieteni.COUNT);
    IF(v_prieteni.COUNT>0) THEN
        FOR i IN v_prieteni.FIRST .. v_prieteni.LAST LOOP
            DBMS_OUTPUT.PUT_LINE(v_prieteni(i));
        end loop;
    ELSE
        DBMS_OUTPUT.PUT_LINE('Utilizatorul nu are prieteni');
    END IF;


    --gasim ultimele grupuri in care a intrat utilizatorul (maxim 3)
    FOR rezulat IN
        (
            SELECT G.NUME_GRUP
            FROM UTILIZATOR_GRUP UG
            JOIN GRUP G ON UG.ID_GRUP = G.ID_GRUP
            WHERE UG.ID_UTILIZATOR=p_id_utilizator
            ORDER BY UG.DATA_ADERARII DESC
        ) LOOP

        IF v_grupuri.COUNT<3 THEN
            v_grupuri.extend;
            v_grupuri(v_grupuri.LAST) := rezulat.NUME_GRUP;
        end if;
    end loop;

    --afisam grupurile
    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('GRUPURI RECENTE:');
    IF v_grupuri.COUNT>0 THEN

        FOR i IN v_grupuri.FIRST .. v_grupuri.LAST LOOP
            DBMS_OUTPUT.PUT_LINE(v_grupuri(i));
        end loop;
    ELSE
        DBMS_OUTPUT.PUT_LINE('Utilizatorul nu face parte din niciun grup');
    end if;


    --cream statistica despre postari, comentarii si reactii
    SELECT COUNT(*)
    INTO v_statistica('Postari')
    FROM POSTARE
    WHERE ID_UTILIZATOR=p_id_utilizator;

    SELECT COUNT(*)
    INTO v_statistica('Comentarii')
    FROM COMENTARIU
    WHERE ID_UTILIZATOR=p_id_utilizator;

    SELECT COUNT(*)
    INTO v_statistica('Reactii')
    FROM REACTIE
    WHERE ID_UTILIZATOR=p_id_utilizator;

    --afisam statistica
    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('STATISTICA ACTIVITATE:');

    DBMS_OUTPUT.PUT_LINE('Postari create: ' || v_statistica('Postari'));
    DBMS_OUTPUT.PUT_LINE('Comentarii scrise: ' || v_statistica('Comentarii'));
    DBMS_OUTPUT.PUT_LINE('Reactii lasate: ' || v_statistica('Reactii'));

end;
/



--apelam procedura
BEGIN
    p_afisare_profil_utilizator(5);
end;
/







-- ex 7
-- Formulați în limbaj natural o problemă pe care să o rezolvați folosind un subprogram stocat
-- independent care să utilizeze 2 tipuri diferite de cursoare studiate, unul dintre acestea fiind cursor
-- parametrizat, dependent de celălalt cursor. Apelați subprogramul.


--Enunt problema
-- Se doreste afisarea postarilor prietenilor unui utilizator.
-- Procedura va folosi un cursor clasic pentru a identifica toti prietenii utilizatorlui,
-- iar apoi un ciclu cursor parametrizat care primeste ca argument id-ul prietenelui curent
-- pentru a afisa postarile acestuia



CREATE OR REPLACE PROCEDURE p_afisare_postari_prieteni(
    p_id_utilizator UTILIZATOR.ID_UTILIZATOR%type
) IS

    --cursor pentru a cauta prietenii
    CURSOR c_prieteni IS
        SELECT U.ID_UTILIZATOR, U.NUME
        FROM PRIETENIE PRT
        JOIN UTILIZATOR U ON PRT.ID_PRIETEN=U.ID_UTILIZATOR
        WHERE PRT.ID_UTILIZATOR = p_id_utilizator AND PRT.STATUS='ACCEPTAT'
        UNION
        SELECT U.ID_UTILIZATOR, U.NUME
        FROM PRIETENIE PRT
        JOIN UTILIZATOR U ON PRT.ID_UTILIZATOR=U.ID_UTILIZATOR
        WHERE PRT.ID_PRIETEN=p_id_utilizator AND PRT.STATUS='ACCEPTAT';

    --cursor pentru postarile unui utilizator
    CURSOR c_postari (c_id_prieten NUMBER) IS
        SELECT P.CONTINUT_TEXT, P.DATA_POSTARII,G.NUME_GRUP
        FROM POSTARE P
        LEFT JOIN GRUP G ON P.ID_GRUP=G.ID_GRUP
        WHERE P.ID_UTILIZATOR=c_id_prieten
        ORDER BY DATA_POSTARII DESC;

        v_nume_utilizator UTILIZATOR.NUME%type;
        v_prieten_id UTILIZATOR.ID_UTILIZATOR%type;
        v_prieten_nume UTILIZATOR.NUME%type;
        v_are_postari BOOLEAN;
BEGIN

    SELECT NUME
    INTO v_nume_utilizator
    FROM UTILIZATOR
    WHERE ID_UTILIZATOR=p_id_utilizator;



    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('----------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Postarile prietenilor lui ' || v_nume_utilizator);
    DBMS_OUTPUT.PUT_LINE('----------------------------------------');
    DBMS_OUTPUT.PUT_LINE(' ');


    OPEN c_prieteni;
    LOOP



        FETCH c_prieteni INTO v_prieten_id, v_prieten_nume;
        EXIT WHEN c_prieteni%NOTFOUND; --iesire cand nu mai sunt randuri

        DBMS_OUTPUT.PUT_LINE(v_prieten_nume || ':');
        DBMS_OUTPUT.PUT_LINE(' ');

        v_are_postari:=FALSE;

        FOR postare IN c_postari(v_prieten_id) LOOP

            v_are_postari:=TRUE;


            DBMS_OUTPUT.PUT_LINE(postare.CONTINUT_TEXT);
            IF postare.NUME_GRUP IS NULL THEN
                    DBMS_OUTPUT.PUT_LINE('Profil');
            ELSE
                    DBMS_OUTPUT.PUT_LINE(postare.NUME_GRUP);
            end if;
            DBMS_OUTPUT.PUT_LINE(postare.DATA_POSTARII);
            DBMS_OUTPUT.PUT_LINE(' ');


        end loop;

        IF v_are_postari = FALSE THEN
            DBMS_OUTPUT.PUT_LINE('Nicio postare');
        end if;


        DBMS_OUTPUT.PUT_LINE('----------');


    end loop;
    CLOSE c_prieteni;

end;
/

BEGIN
    p_afisare_postari_prieteni(5);
end;
/


-- ex 8
-- Formulați în limbaj natural o problemă pe care să o rezolvați folosind un subprogram stocat
-- independent de tip funcție care să utilizeze într-o singură comandă SQL 3 dintre tabelele create.
-- Tratați toate excepțiile care pot apărea, incluzând excepțiile predefinite NO_DATA_FOUND și
-- TOO_MANY_ROWS. Apelați subprogramul astfel încât să evidențiați toate cazurile tratate.

--Enunt problema:
-- Se dorește căutarea unui text în toate postările existente.
-- Funcția căuta în conținutul text al postărilor și afișează postarea
-- (autorul, locația tot conținutul postării) în care se regăsește secvența de tip text căutată.
-- Dacă nu se găsește nicio postare sau dacă sunt prea multe postări care conțin textul căutat,
-- se va afișa o eroare.


CREATE OR REPLACE FUNCTION f_cauta_continut (
    p_text_cautat IN VARCHAR2
) RETURN VARCHAR2
IS
    v_rezultat VARCHAR2(256);
    v_nume_utilizator VARCHAR2(256);
    v_nume_grup VARCHAR2(256);
    v_continut_text VARCHAR2(256);
BEGIN


    SELECT U.NUME, NVL(G.NUME_GRUP,'Profil Personal'), P.CONTINUT_TEXT
    INTO v_nume_utilizator, v_nume_grup, v_continut_text
    FROM POSTARE P
    JOIN UTILIZATOR U ON P.ID_UTILIZATOR = U.ID_UTILIZATOR
    LEFT JOIN GRUP G ON P.ID_GRUP = G.ID_GRUP
    WHERE UPPER(P.CONTINUT_TEXT) LIKE ('%' || TRIM(UPPER(p_text_cautat)) || '%');

    v_rezultat := 'Postare gasita cu textul "'||p_text_cautat
                      || '" | Autor: ' || v_nume_utilizator
                      || ' | Locatie: ' || v_nume_grup
                      ||'  | Cotinut : "'|| v_continut_text || '"';

    return v_rezultat;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Eroare: Nu s a gasit nicio postare cu textul "' || p_text_cautat || '"';
    WHEN TOO_MANY_ROWS THEN
        RETURN 'Eroare: Prea multe postari contin textul "' || p_text_cautat || '"';
    WHEN OTHERS THEN
        RETURN 'Eroare necunoscuta';
end;
/


BEGIN
    DBMS_OUTPUT.PUT_LINE(f_cauta_continut('ASC '));
end;
/
BEGIN
    DBMS_OUTPUT.PUT_LINE(f_cauta_continut('la'));
end;
/
BEGIN
    DBMS_OUTPUT.PUT_LINE(f_cauta_continut('BANANA '));
end;
/




--ex 9
-- Formulați în limbaj natural o problemă pe care să o rezolvați folosind un subprogram stocat
-- independent de tip procedură care să aibă minim 2 parametri și să utilizeze într-o singură
-- comandă SQL 5 dintre tabelele create. Definiți minim 2 excepții proprii, altele decât cele
-- predefinite la nivel de sistem. Apelați subprogramul astfel încât să evidențiați toate cazurile definite
-- și tratate.

-- Enunt problema
--Să dorește realizarea unui sistem de notificări care afișează un număr stabilit de notificări pentru un anumit utilizator.
-- Procedura primește ca parametru id-ul unui utilizator, un număr maxim de notificări
-- și afișează cele mai recente notificări ale utilizatorului (cereri de prietenie, reacții și comentarii).

CREATE OR REPLACE PROCEDURE p_notificari(
    p_id_utilizator IN VARCHAR2,
    p_limita IN NUMBER
)
IS
    v_id_utilizator UTILIZATOR.ID_UTILIZATOR%type;
    v_nume_utilizator UTILIZATOR.NUME%type;
    v_nr_notificari NUMBER :=0;

    exceptie_limita_invalida EXCEPTION;
    exceptie_user_inexistent EXCEPTION;
    exceptie_zero_notificari EXCEPTION;
BEGIN

    --verificam limita notificarilor
    BEGIN
        --nu putem avea limita negativa notificari sau un numar prea mare
        IF p_limita <=0 OR p_limita>=256 THEN
            RAISE exceptie_limita_invalida;
        end if;
    END;


    --verificam daca exista utilizatorul
    BEGIN
        SELECT U.ID_UTILIZATOR,U.NUME
        INTO v_id_utilizator,v_nume_utilizator
        FROM UTILIZATOR U
        WHERE U.ID_UTILIZATOR=p_id_utilizator;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE exceptie_user_inexistent;
    END;


    DBMS_OUTPUT.PUT_LINE(' ');
    DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Ultimele '|| p_limita || ' notificari ale utilizatorului ' || v_nume_utilizator);
    DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE(' ');


    FOR rezultat IN
        (
            SELECT * FROM
                         (
                              --cereri de prietenie
                              SELECT U.NUME || ' ti a trimis o cere de prietenie' AS mesaj,
                                     P.DATA_TRIMITERII                           AS data_notificare
                              FROM PRIETENIE P
                                       JOIN UTILIZATOR U ON P.ID_UTILIZATOR = U.ID_UTILIZATOR
                              WHERE P.ID_PRIETEN = p_id_utilizator
                              --AND P.STATUS='ASTEPTARE' AND P.DATA_TRIMITERII >= SYSDATE - p_nr_zile


                              UNION

                              --comentarii
                              SELECT U.NUME || 'a comentat "' || C.CONTINUT_TEXT || '" la postarea ta',
                                     C.DATA_POSTARII AS data_notificare
                              FROM COMENTARIU C
                                       JOIN POSTARE POST ON C.ID_POSTARE = POST.ID_POSTARE
                                       JOIN UTILIZATOR U ON C.ID_UTILIZATOR = U.ID_UTILIZATOR
                              WHERE POST.ID_UTILIZATOR = p_id_utilizator

                              UNION

                              --reactii
                              SELECT U.NUME || ' a reactionat cu ' || R.TIP_REACTIE || ' la postarea ta' AS mesaj,
                                     R.DATA_TRIMITERII                                                   AS data_notificare

                              FROM REACTIE R
                                       JOIN POSTARE P ON R.ID_POSTARE = P.ID_POSTARE
                                       JOIN UTILIZATOR U ON R.ID_UTILIZATOR = U.ID_UTILIZATOR
                              WHERE P.ID_UTILIZATOR = p_id_utilizator


                              ORDER BY 2 DESC
                        )WHERE ROWNUM<=p_limita
        ) LOOP
            DBMS_OUTPUT.PUT_LINE(rezultat.mesaj);
            DBMS_OUTPUT.PUT_LINE(rezultat.data_notificare);
            DBMS_OUTPUT.PUT_LINE(' ');

            v_nr_notificari:=v_nr_notificari+1;
        end loop;

    IF v_nr_notificari = 0 THEN
        RAISE exceptie_zero_notificari;
    end if;

EXCEPTION
    WHEN exceptie_user_inexistent THEN
        RAISE_APPLICATION_ERROR(-20010, 'Eroare: Utilizatorul nu a fost gasit');
    WHEN exceptie_zero_notificari THEN
        RAISE_APPLICATION_ERROR(-20011, 'Eroare:Utilizatorul nu are notificari');
    WHEN exceptie_limita_invalida THEN
        RAISE_APPLICATION_ERROR(-20012, 'Eroare: Limita de notificari invalida');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20013, 'Eroare necunoscuta');


end;
/



BEGIN
    p_notificari(1,2);
end;
/


BEGIN
    p_notificari(1,4);
end;
/


--exceptie: utilizatorul nu exista
BEGIN
    p_notificari(100,2);
end;
/


--exceptie: limita de notificari invalida
BEGIN
    p_notificari(1,-1);
end;
/


--exceptie: nu exista notificari
BEGIN
    p_notificari(7,2);
end;
/





--ex 10
-- Definiți un trigger de tip LMD la nivel de comandă. Declanșați trigger-ul.

--Enunt problema
--Se interzice adăugarea, modificarea sau ștergerea postărilor cât timp serverul este în mentenanță.

--cream un pakcet pentru a simula o variabila globala
CREATE OR REPLACE PACKAGE p_stare_server IS
    v_mentenanta BOOLEAN :=FALSE;
END;
/

CREATE OR REPLACE TRIGGER trigger_modificare_mentenanta
BEFORE INSERT OR UPDATE OR DELETE ON POSTARE
BEGIN
    IF p_stare_server.v_mentenanta = TRUE THEN
        RAISE_APPLICATION_ERROR(-20014,'Sistemul este in mentenanta! Nu puteti modifica, adauga sau sterge postari!');
    end if;
end;
/


BEGIN
    --incercam inserarea cat timp serverul nu este in mentenanta
    DBMS_OUTPUT.PUT_LINE('Serverul este in stara normala');
    BEGIN
        INSERT INTO POSTARE (ID_UTILIZATOR, CONTINUT_TEXT)
        VALUES (1,'Test Postare');
        DBMS_OUTPUT.PUT_LINE('Succes: Postare Creata');
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE(SQLERRM);
    end;

    rollback;

    p_stare_server.v_mentenanta:=True;
    DBMS_OUTPUT.PUT_LINE('Serverul este in stare de  mentenanta');


    BEGIN
        INSERT INTO POSTARE (ID_UTILIZATOR, CONTINUT_TEXT)
        VALUES (1,'Test Postare');
        DBMS_OUTPUT.PUT_LINE('Succes: Postare Creata');
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE(SQLERRM);
    end;

    p_stare_server.v_mentenanta:=False;
end;
/



--ex 11
-- Definiți un trigger de tip LMD la nivel de linie. Declanșați trigger-ul.

-- Enuntul problemei
--Se dorește moderarea comentariilor. Un comentariu nu poate fi lăsat dacă conține cuvinte interzise.

CREATE OR REPLACE TRIGGER trigger_limbaj_licentios
BEFORE INSERT OR UPDATE OF CONTINUT_TEXT ON COMENTARIU
FOR EACH ROW
BEGIN
    IF INSTR(UPPER(:NEW.CONTINUT_TEXT),'CUVANT INTERZIS') > 0 THEN
        RAISE_APPLICATION_ERROR(-20015, 'Comentariul contine cuvinte interzie!');
    end if;
END;
/



BEGIN
        INSERT INTO COMENTARIU (ID_UTILIZATOR, ID_POSTARE, CONTINUT_TEXT)
        VALUES (1,1,
        'Comentariu care contine un cuvant decent'
       );
        rollback ;
End;
/
BEGIN
    INSERT INTO COMENTARIU (ID_UTILIZATOR, ID_POSTARE, CONTINUT_TEXT)
    VALUES (1,1,
        'Comentariu care contine un cuvant interzis'
       );
    rollback;
end;
/


--ex 12
--Definiți un trigger de tip LDD. Declanșați trigger-ul.

-- Enunt Problema
-- Se dorește monitorizare tuturor modificărilor asupra bazei de date.
-- Orice instrucție de tip LDD va fi înregistrată într-un istoric de schimbări.

-- DROP TRIGGER trigger_schimbari_baza_date;
-- /
-- DROP TABLE ISTORIC_SCHIMBARI;
-- /

CREATE TABLE ISTORIC_SCHIMBARI
(
    id_schimbare NUMBER GENERATED BY DEFAULT AS IDENTITY,
    utilizator varchar2(256),
    comanda_rulata VARCHAR2(256),
    tabel_modificat VARCHAR2(256),
    data DATE
);
/

CREATE OR REPLACE TRIGGER trigger_schimbari_baza_date
AFTER CREATE OR DROP OR ALTER ON SCHEMA
BEGIN
    INSERT INTO ISTORIC_SCHIMBARI (utilizator, comanda_rulata, tabel_modificat,data)
    VALUES (
            USER,
            SYS.SYSEVENT,
            SYS.DICTIONARY_OBJ_NAME,
            SYSDATE
           );
end;
/



BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE TABEL_TEST (id_number NUMBER)';

    EXECUTE IMMEDIATE 'ALTER TABLE TABEL_TEST ADD (nume VARCHAR2(256))';

    EXECUTE IMMEDIATE 'DROP TABLE TABEL_TEST';

END;
/
SELECT * FROM ISTORIC_SCHIMBARI;
/
